# config.py — EDIT THIS FIRST before uploading to Pico W

WIFI_SSID = "YourWiFiName"
WIFI_PASSWORD = "YourWiFiPassword"

MQTT_BROKER = "broker.hivemq.com"
MQTT_PORT = 1883
MQTT_TOPIC_ALERT = "safety/alert"
MQTT_TOPIC_STATUS = "safety/status"
DEVICE_ID = "SAFETY_001"

SOS_PHONE_NUMBER = "+91XXXXXXXXXX"
SOS_PHONE_NUMBER_2 = "+91XXXXXXXXXX"

FALL_ACCEL_THRESHOLD = 2.5
AUDIO_THREAT_THRESHOLD = 2000
MOTION_SENSITIVITY = 0.8

SENSOR_POLL_MS = 100
PHOTO_INTERVAL_S = 5
HEARTBEAT_INTERVAL_S = 30
